### ISSUE TITLE
MetalRenderingTools Is private

### ISSUE THREAD

**Issue by adamnemecek** [eugenebokhan/Metal-Text-Rendering#1]
Hey, I’m trying to figure out how to render text with metal and came across this repo but MetalRenderingTools is private (I’m guessing).

**Comment by eugenebokhan** [comment]
@adamnemecek Hi! I'm sorry, looks like when I played with the repo settings I forgot to make it public. Please check it once again.

**Comment by adamnemecek** [comment]
Thanks!
